{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    filterAttrs
    mapAttrs
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    types
    ;

  enabledUsers = filterAttrs (
    _: userCfg: userCfg.domains.editors.helix.enable or false
  ) config.home-manager.users;

  anyEnabled = enabledUsers != { };

  helixHomeModule =
    {
      config,
      ...
    }:
    let
      cfg = config.domains.editors.helix;
    in
    {
      options.domains.editors.helix = {
        enable = mkEnableOption "helix text editor";

        extraConfig = mkOption {
          type = types.lines;
          default = "";
          description = ''
            Extra configuration to add to config.toml.
            See https://docs.helix-editor.com/configuration.html for options.
          '';
          example = ''
            [editor]
            line-number = "relative"
            auto-save = true

            [editor.cursor-shape]
            insert = "bar"
          '';
        };
      };

      config = mkIf cfg.enable (mkMerge [
        {
          xdg.configFile."helix/config.toml".text = ''
            # Helix configuration
            # Generated by domains.editors.helix

            ${cfg.extraConfig}
          '';

          home.packages = [ pkgs.helix ];
        }

        # Nushell integration: set EDITOR and VISUAL
        (mkIf (config.domains.shell.nushell.enable or false) {
          programs.nushell.extraEnv = ''
            # Set EDITOR and VISUAL
            $env.EDITOR = "hx"
            $env.VISUAL = $env.EDITOR
          '';
        })
      ]);
    };
in
{
  config = mkMerge [
    {
      home-manager.sharedModules = [ helixHomeModule ];
    }

    (mkIf anyEnabled {
      environment.systemPackages = [ pkgs.helix ];
    })

    (mkIf (anyEnabled && (config.domains.storage.btrfs.preservation.enable or false)) {
      domains.storage.btrfs.preservation.mounts."/persist" = {
        users = mapAttrs (username: _: {
          directories = [
            ".config/helix"
            ".local/state/helix"
            ".cache/helix"
          ];
        }) enabledUsers;
      };
    })
  ];
}
