{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    filterAttrs
    mapAttrs
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    types
    ;

  # Collect all users with atuin enabled
  enabledUsers = filterAttrs (
    _: userCfg: userCfg.domains.shell.atuin.enable or false
  ) config.home-manager.users;

  anyEnabled = enabledUsers != { };

  # Home-manager module that provides per-user options
  atuinHomeModule =
    {
      config,
      ...
    }:
    let
      cfg = config.domains.shell.atuin;
    in
    {
      options.domains.shell.atuin = {
        enable = mkEnableOption "atuin magical shell history";

        sync = {
          enable = mkOption {
            type = types.bool;
            default = false;
            description = "Enable atuin sync.";
          };

          keyFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            description = ''
              Path to the atuin encryption key file (from SOPS).
              If null, you must run 'atuin login' or 'atuin register' manually.
            '';
          };

          sessionFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            description = ''
              Path to the atuin session token file (from SOPS).
              If null, you must run 'atuin login' manually.
            '';
          };
        };
      };

      config = mkIf cfg.enable (
        lib.mkMerge [
          {
            # Generate opinionated atuin config
            xdg.configFile."atuin/config.toml".text = ''
              # Atuin configuration
              # Generated by domains.shell.atuin

              # Search settings
              search_mode = "fuzzy"
              filter_mode = "global"
              style = "compact"

              # Sync settings
              ${
                if cfg.sync.enable then
                  ''
                    auto_sync = true
                    sync_frequency = "10m"
                    sync_address = "https://api.atuin.sh"
                  ''
                else
                  ''
                    auto_sync = false
                    sync_frequency = "0"
                  ''
              }

              # UI settings
              dialect = "uk"
              inline_height = 20
              show_preview = true

              # History settings
              update_check = false
            '';

            home.packages = [ pkgs.atuin ];
          }

          # Link encryption key from SOPS
          (lib.mkIf (cfg.sync.enable && cfg.sync.keyFile != null) {
            xdg.configFile."atuin/key".source = cfg.sync.keyFile;
          })

          # Link session token from SOPS
          (lib.mkIf (cfg.sync.enable && cfg.sync.sessionFile != null) {
            xdg.configFile."atuin/session".source = cfg.sync.sessionFile;
          })
        ]
      );
    };
in
{
  config = mkMerge [
    # Inject the atuin home-manager module into all users
    {
      home-manager.sharedModules = [ atuinHomeModule ];
    }

    # System-level configuration when any user has atuin enabled
    (mkIf anyEnabled {
      # Ensure atuin is available system-wide
      environment.systemPackages = [ pkgs.atuin ];
    })

    # Conditional persistence for all enabled users
    (mkIf (anyEnabled && (config.domains.storage.btrfs.preservation.enable or false)) {
      domains.storage.btrfs.preservation.mounts."/persist" = {
        users = mapAttrs (username: _: {
          directories = [
            ".local/share/atuin"
            ".config/atuin"
          ];
        }) enabledUsers;
      };
    })
  ];
}
