{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    concatStringsSep
    filterAttrs
    mapAttrs
    mapAttrsToList
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    optionalString
    types
    ;

  enabledUsers = filterAttrs (
    _: userCfg: userCfg.domains.shell.nushell.enable or false
  ) config.home-manager.users;

  anyEnabled = enabledUsers != { };

  nushellHomeModule =
    {
      config,
      ...
    }:
    let
      cfg = config.domains.shell.nushell;

      defaultPlugins = with pkgs.nushellPlugins; [
        polars
        gstat
        formats
        query
      ];

      envNuContent = ''
        # Nushell environment configuration
        # Generated by domains.shell.nushell

        ${optionalString (config.domains.editors.helix.enable or false) ''
          # Set EDITOR and VISUAL
          $env.EDITOR = "hx"
          $env.VISUAL = $env.EDITOR
        ''}

        ${optionalString (config.domains.tools.yazi.enable or false) ''
          # Yazi wrapper for cd-on-quit
          def --env ${config.domains.tools.yazi.wrapperName or "y"} [...args] {
            let tmp = (mktemp -t "yazi-cwd.XXXXXX")
            yazi ...$args --cwd-file $tmp
            let cwd = (open $tmp)
            if $cwd != "" and $cwd != $env.PWD {
              cd $cwd
            }
            rm -f $tmp
          }
        ''}

        # User's extra env configuration
        ${cfg.extraEnv}
      '';

      configNuContent = ''
        # Nushell configuration
        # Generated by domains.shell.nushell

        # Basic configuration
        $env.config = {
          show_banner: false
          use_kitty_protocol: true

          table: {
            mode: rounded
            index_mode: auto
            show_empty: true
          }

          filesize: {
            metric: false
            format: "auto"
          }

          cursor_shape: {
            vi_insert: line
            vi_normal: block
          }

          history: {
            max_size: 100000
            sync_on_enter: true
            file_format: "sqlite"
          }
        }

        # Register plugins
        plugin add ${pkgs.nushellPlugins.polars}/bin/nu_plugin_polars
        plugin add ${pkgs.nushellPlugins.gstat}/bin/nu_plugin_gstat
        plugin add ${pkgs.nushellPlugins.formats}/bin/nu_plugin_formats
        plugin add ${pkgs.nushellPlugins.query}/bin/nu_plugin_query

        # Shell aliases
        ${concatStringsSep "\n" (mapAttrsToList (name: value: "alias ${name} = ${value}") cfg.shellAliases)}

        ${optionalString (config.domains.shell.starship.enable or false) ''
          # Initialize starship prompt
          mkdir ~/.cache/starship
          starship init nu | save -f ~/.cache/starship/init.nu
          use ~/.cache/starship/init.nu
        ''}

        ${optionalString (config.domains.shell.zoxide.enable or false) ''
          # Initialize zoxide
          mkdir ~/.cache/zoxide
          zoxide init nushell | save -f ~/.cache/zoxide/init.nu
          use ~/.cache/zoxide/init.nu
        ''}

        ${optionalString (config.domains.shell.atuin.enable or false) ''
          # Initialize atuin
          mkdir ~/.cache/atuin
          atuin init nu | save -f ~/.cache/atuin/init.nu
          use ~/.cache/atuin/init.nu
        ''}

        ${optionalString (config.domains.shell.carapace.enable or false) ''
          # Initialize carapace completions
          mkdir ~/.cache/carapace
          carapace _carapace nushell | save -f ~/.cache/carapace/init.nu
          use ~/.cache/carapace/init.nu
        ''}

        ${optionalString (config.domains.development.direnv.enable or false) ''
          # Initialize direnv
          mkdir ~/.config/nushell/scripts
          direnv hook nu | save -f ~/.config/nushell/scripts/direnv.nu
          use ~/.config/nushell/scripts/direnv.nu
        ''}

        # User's extra configuration
        ${cfg.extraConfig}
      '';
    in
    {
      options.domains.shell.nushell = {
        enable = mkEnableOption "nushell shell";

        shellAliases = mkOption {
          type = types.attrsOf types.str;
          default = { };
          description = "Shell aliases for nushell.";
          example = {
            ll = "ls -l";
            la = "ls -la";
          };
        };

        extraEnv = mkOption {
          type = types.lines;
          default = "";
          description = "Extra configuration to add to env.nu.";
        };

        extraConfig = mkOption {
          type = types.lines;
          default = "";
          description = "Extra configuration to add to config.nu.";
        };
      };

      config = mkIf cfg.enable {
        xdg.configFile."nushell/config.nu".text = configNuContent;
        xdg.configFile."nushell/env.nu".text = envNuContent;

        home.packages = defaultPlugins;
      };
    };
in
{
  config = mkMerge [
    {
      home-manager.sharedModules = [ nushellHomeModule ];
    }

    (mkIf anyEnabled {
      environment.shells = [ pkgs.nushell ];

      environment.systemPackages = [ pkgs.nushell ];

      users.users = mapAttrs (username: _: {
        shell = pkgs.nushell;
      }) enabledUsers;
    })

    (mkIf (anyEnabled && (config.domains.storage.btrfs.preservation.enable or false)) {
      domains.storage.btrfs.preservation.mounts."/persist" = {
        users = mapAttrs (username: _: {
          directories = [
            ".config/nushell"
            ".local/share/nushell"
          ];
        }) enabledUsers;
      };
    })
  ];
}
