{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    concatMapStringsSep
    concatStringsSep
    filterAttrs
    literalExpression
    mapAttrs
    mapAttrsToList
    mkIf
    mkMerge
    mkOption
    optionalString
    types
    ;

  # Collect all users with nushell enabled
  enabledUsers = filterAttrs (
    _: userCfg: userCfg.domains.shell.nushell.enable or false
  ) config.home-manager.users;

  # Check if any user has nushell enabled
  anyEnabled = enabledUsers != { };

  # Home-manager module that provides per-user options
  nushellHomeModule =
    {
      config,
      ...
    }:
    let
      cfg = config.domains.shell.nushell;

      # Generate plugin registration commands
      mkPluginRegistrations =
        let
          # Extract plugin binary paths from packages
          getPluginBinary =
            pkg:
            let
              name = pkg.pname or (builtins.parseDrvName pkg.name).name;
            in
            "${pkg}/bin/${name}";

          pluginPaths = map getPluginBinary cfg.plugins;
        in
        concatMapStringsSep "\n" (path: "plugin add ${path}") pluginPaths;

      # Generate env.nu content
      envNuContent = ''
        # Nushell environment configuration
        # Generated by domains.shell.nushell

        # Environment variables
        ${concatStringsSep "\n" (
          mapAttrsToList (name: value: "$env.${name} = ${builtins.toJSON value}") cfg.environmentVariables
        )}

        ${optionalString (config.domains.editors.helix.enable or false) ''
          # Set EDITOR and VISUAL
          $env.EDITOR = "${config.domains.editors.helix.command or "hx"}"
          $env.VISUAL = $env.EDITOR
        ''}

        ${optionalString (config.domains.tools.yazi.enable or false) ''
          # Yazi wrapper for cd-on-quit
          def --env ${config.domains.tools.yazi.wrapperName or "y"} [...args] {
            let tmp = (mktemp -t "yazi-cwd.XXXXXX")
            yazi ...$args --cwd-file $tmp
            let cwd = (open $tmp)
            if $cwd != "" and $cwd != $env.PWD {
              cd $cwd
            }
            rm -f $tmp
          }
        ''}

        # User's extra env configuration
        ${cfg.extraEnv}
      '';

      # Generate config.nu content
      configNuContent = ''
        # Nushell configuration
        # Generated by domains.shell.nushell

        # Basic configuration
        $env.config = {
          show_banner: false
          use_kitty_protocol: true

          table: {
            mode: rounded
            index_mode: auto
            show_empty: true
          }

          filesize: {
            metric: false
            format: "auto"
          }

          cursor_shape: {
            vi_insert: line
            vi_normal: block
          }

          history: {
            max_size: 100000
            sync_on_enter: true
            file_format: "sqlite"
          }
        }

        # Register plugins
        ${mkPluginRegistrations}

        # Shell aliases
        ${concatStringsSep "\n" (mapAttrsToList (name: value: "alias ${name} = ${value}") cfg.shellAliases)}

        ${optionalString (config.domains.shell.starship.enable or false) ''
          # Initialize starship prompt
          mkdir ~/.cache/starship
          starship init nu | save -f ~/.cache/starship/init.nu
          use ~/.cache/starship/init.nu
        ''}

        ${optionalString (config.domains.shell.zoxide.enable or false) ''
          # Initialize zoxide
          mkdir ~/.cache/zoxide
          zoxide init nushell | save -f ~/.cache/zoxide/init.nu
          use ~/.cache/zoxide/init.nu
        ''}

        ${optionalString (config.domains.shell.atuin.enable or false) ''
          # Initialize atuin
          mkdir ~/.cache/atuin
          atuin init nu | save -f ~/.cache/atuin/init.nu
          use ~/.cache/atuin/init.nu
        ''}

        ${optionalString (config.domains.shell.carapace.enable or false) ''
          # Initialize carapace completions
          mkdir ~/.cache/carapace
          carapace _carapace nushell | save -f ~/.cache/carapace/init.nu
          use ~/.cache/carapace/init.nu
        ''}

        ${optionalString (config.domains.development.direnv.enable or false) ''
          # Initialize direnv
          mkdir ~/.config/nushell/scripts
          direnv hook nu | save -f ~/.config/nushell/scripts/direnv.nu
          use ~/.config/nushell/scripts/direnv.nu
        ''}

        # User's extra configuration
        ${cfg.extraConfig}
      '';
    in
    {
      options.domains.shell.nushell = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = "Enable nushell as the default shell for this user.";
        };

        plugins = mkOption {
          type = types.listOf types.package;
          default = with pkgs.nushellPlugins; [
            polars
            gstat
            formats
            query
          ];
          defaultText = literalExpression ''
            with pkgs.nushellPlugins; [
              polars
              gstat
              formats
              query
            ]
          '';
          description = ''
            Nushell plugin packages to install and register.
            Plugins are automatically registered in config.nu.

            Note: Some plugins may be marked as broken in nixpkgs.
            Check plugin availability before adding.
          '';
          example = literalExpression ''
            with pkgs.nushellPlugins; [
              polars
              gstat
              formats
              query
              desktop_notifications
            ]
          '';
        };

        shellAliases = mkOption {
          type = types.attrsOf types.str;
          default = { };
          description = "Shell aliases for nushell.";
          example = {
            ll = "ls -l";
            la = "ls -la";
          };
        };

        environmentVariables = mkOption {
          type = types.attrsOf types.str;
          default = { };
          description = "Environment variables to set in nushell.";
        };

        extraEnv = mkOption {
          type = types.lines;
          default = "";
          description = "Extra configuration to add to env.nu.";
        };

        extraConfig = mkOption {
          type = types.lines;
          default = "";
          description = "Extra configuration to add to config.nu.";
        };
      };

      config = mkIf cfg.enable {
        # Generate nushell config files
        xdg.configFile."nushell/config.nu".text = configNuContent;
        xdg.configFile."nushell/env.nu".text = envNuContent;

        # Install plugin packages
        home.packages = cfg.plugins;
      };
    };
in
{
  config = mkMerge [
    # Inject the nushell home-manager module into all users
    {
      home-manager.sharedModules = [ nushellHomeModule ];
    }

    # System-level configuration when any user has nushell enabled
    (mkIf anyEnabled {
      # Add nushell to /etc/shells so it can be used as a login shell
      environment.shells = [ pkgs.nushell ];

      # Ensure nushell is available system-wide
      environment.systemPackages = [ pkgs.nushell ];

      # Set nushell as default shell for enabled users
      users.users = mapAttrs (username: _: {
        shell = pkgs.nushell;
      }) enabledUsers;
    })

    # Conditional persistence for all enabled users
    (mkIf (anyEnabled && (config.domains.storage.btrfs.preservation.enable or false)) {
      domains.storage.btrfs.preservation.mounts."/persist" = {
        users = mapAttrs (username: _: {
          directories = [
            ".config/nushell"
            ".local/share/nushell"
          ];
        }) enabledUsers;
      };
    })
  ];
}
