{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    filterAttrs
    mapAttrs
    mkEnableOption
    mkIf
    mkMerge
    ;

  # Collect all users with direnv enabled
  enabledUsers = filterAttrs (
    _: userCfg: userCfg.domains.development.direnv.enable or false
  ) config.home-manager.users;

  anyEnabled = enabledUsers != { };

  # Home-manager module that provides per-user options
  direnvHomeModule =
    {
      config,
      ...
    }:
    let
      cfg = config.domains.development.direnv;
    in
    {
      options.domains.development.direnv = {
        enable = mkEnableOption "direnv environment switcher";
      };

      config = mkIf cfg.enable {
        # Generate opinionated direnv config with nix-direnv integration
        xdg.configFile."direnv/direnv.toml".text = ''
          # Direnv configuration
          # Generated by domains.development.direnv

          [global]
          load_dotenv = true
          warn_timeout = "30s"
        '';

        home.packages = [
          pkgs.direnv
          pkgs.nix-direnv
        ];
      };
    };
in
{
  config = mkMerge [
    # Inject the direnv home-manager module into all users
    {
      home-manager.sharedModules = [ direnvHomeModule ];
    }

    # System-level configuration when any user has direnv enabled
    (mkIf anyEnabled {
      # Ensure direnv is available system-wide
      environment.systemPackages = [
        pkgs.direnv
        pkgs.nix-direnv
      ];
    })

    # Conditional persistence for all enabled users
    (mkIf (anyEnabled && (config.domains.storage.btrfs.preservation.enable or false)) {
      domains.storage.btrfs.preservation.mounts."/persist" = {
        users = mapAttrs (username: _: {
          directories = [
            ".local/share/direnv"
            ".cache/direnv"
          ];
        }) enabledUsers;
      };
    })
  ];
}
