{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    filterAttrs
    mapAttrs
    mkEnableOption
    mkIf
    mkMerge
    ;

  enabledUsers = filterAttrs (
    _: userCfg: userCfg.domains.development.direnv.enable or false
  ) config.home-manager.users;

  anyEnabled = enabledUsers != { };

  direnvHomeModule =
    {
      config,
      ...
    }:
    let
      cfg = config.domains.development.direnv;
    in
    {
      options.domains.development.direnv = {
        enable = mkEnableOption "direnv environment switcher";
      };

      config = mkIf cfg.enable {
        xdg.configFile."direnv/direnv.toml".text = ''
          # Direnv configuration
          # Generated by domains.development.direnv

          [global]
          load_dotenv = true
          warn_timeout = "30s"
        '';

        home.packages = [
          pkgs.direnv
          pkgs.nix-direnv
        ];
      };
    };
in
{
  config = mkMerge [
    {
      home-manager.sharedModules = [ direnvHomeModule ];
    }

    (mkIf anyEnabled {
      environment.systemPackages = [
        pkgs.direnv
        pkgs.nix-direnv
      ];
    })

    (mkIf (anyEnabled && (config.domains.storage.btrfs.preservation.enable or false)) {
      domains.storage.btrfs.preservation.mounts."/persist" = {
        users = mapAttrs (username: _: {
          directories = [
            ".local/share/direnv"
            ".cache/direnv"
          ];
        }) enabledUsers;
      };
    })
  ];
}
