name: Cachix Push

on:
  push:
    branches:
      - main

jobs:
  cachix:
    name: Build and Push to Cachix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - odysseus
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: maxbullett
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and push ${{ matrix.host }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --print-build-logs \
            --show-trace
