name: Flake Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Validate Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Configure Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run flake check
        run: |
          nix flake check --print-build-logs --show-trace
